version: '2'
services:
    personal_data-app:
        image: personal_data
        external_links:
            - personal_data-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/personal_data?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    personal_data-mysql:
        extends:
            file: mysql.yml
            service: personal_data-mysql
